# Generated by Django 2.0.6 on 2018-07-02 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans_auth', to=settings.AUTH_USER_MODEL),
        ),
    ]
