# Generated by Django 2.0.6 on 2018-07-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='a_modified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Answer Modified'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
