# Generated by Django 2.0.6 on 2018-08-11 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0006_question_q_modified_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteAnswerMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.BinaryField(verbose_name='Action')),
                ('upvote_date', models.DateTimeField(verbose_name='Date Upvoted')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Answer')),
                ('upvote_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='upvoteanswermod',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='upvoteanswermod',
            name='upvote_user',
        ),
        migrations.DeleteModel(
            name='UpvoteAnswerMod',
        ),
    ]
