# Generated by Django 2.0.6 on 2018-08-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_auto_20180811_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voteanswermod',
            old_name='upvote_date',
            new_name='vote_date',
        ),
        migrations.RenameField(
            model_name='voteanswermod',
            old_name='upvote_user',
            new_name='vote_user',
        ),
        migrations.AlterField(
            model_name='voteanswermod',
            name='action_taken',
            field=models.SmallIntegerField(verbose_name='Action Vote'),
        ),
    ]
