# Generated by Django 2.0.6 on 2018-08-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0011_auto_20180812_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
