# Generated by Django 2.0.6 on 2018-08-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0014_auto_20180812_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answercomment',
            name='answer',
        ),
        migrations.DeleteModel(
            name='AnswerComment',
        ),
    ]
