# Generated by Django 2.0.6 on 2018-08-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0019_auto_20180826_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicstore',
            name='topic_dp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
