# Generated by Django 2.0.6 on 2018-08-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0020_topicstore_topic_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_cred',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
