# Generated by Django 2.0.6 on 2018-09-03 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0022_followtopic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followtopic',
            old_name='fuser',
            new_name='f_user',
        ),
        migrations.AddField(
            model_name='followtopic',
            name='f_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Follow Date'),
            preserve_default=False,
        ),
    ]
