# Generated by Django 2.0.6 on 2018-10-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0025_followquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='studied',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
